apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-readonly-role-binding
subjects:
  - kind: User
    name: "helloworld-app-developer@southern-flash-289008.iam.gserviceaccount.com"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer-readonly-role
  apiGroup: rbac.authorization.k8s.io
