name: Build, Push Docker Image

on:
  push:
    branches:
      - develop
    # tags:
    #   - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      ## Can run in docker build as well we split better organization of steps ##
      ## For support more features like report, hook, conditional in CI/CD ##
      # Dependency check
      - name : govulncheck check
        uses : golang/govulncheck-action@v1
        with:
          go-version-input: 1.21
          go-package: ./...
      # Static code analysis
      - name: gosec check
        uses: securego/gosec@master
        with:
          args: ./...

      - name: Build and Push Docker image with commit ID and branch or tag
        env:
          COMMIT_ID: ${{ github.sha }}
          APP_NAME: ${{ vars.APP_NAME }}
        run: |
          COMMIT_ID_SHORT=$(echo "${{ github.sha }}" | cut -c1-7)
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ github.ref_name }}-${COMMIT_ID_SHORT} .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ github.ref_name }}-${COMMIT_ID_SHORT}

      - name: Update Nonprod deployment.yaml with new image tag
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          APP_NAME: ${{ vars.APP_NAME }}
        run: |
          COMMIT_ID_SHORT=$(echo "${{ github.sha }}" | cut -c1-7)
          sed -i "s|image: .*$|image: ${{ secrets.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ github.ref_name }}-${COMMIT_ID_SHORT}|" ./overlays/nonprod/deployment.yaml
          git config --global user.name "lychees40"
          git config --global user.email "lychees40@users.noreply.github.com"
          git add ./overlays/nonprod/deployment.yaml
          git commit -m "Update deployment.yaml with image tag ${{ github.ref_name }}-${COMMIT_ID_SHORT}"
          git push
